#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

bun concurrently -g \
	"bun lint-staged --concurrent false" \
	"bun typecheck" \
	"git diff --cached --name-only | npx cspell --no-summary --no-progress --no-must-find-files --file-list stdin"
