#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run env -- concurrently -g \
"pnpm lint-staged --concurrent false" \
"pnpm typecheck" \
"git diff --cached --name-only | npx cspell --no-summary --no-progress --no-must-find-files --file-list stdin" \

