name: 'PR Tests'
on:
  pull_request:
    branches: [main, develop]

jobs:
  pr-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 18.13.0

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run lint and type checks
        run: |
          bun concurrently -g \
          "bun lint" \
          "bun typecheck" \
          "bun prettier --check --ignore-unknown ./" \
          "bun cspell ./ --no-progress --no-must-find-files"
