name: 'PR Tests'
on:
  pull_request:
    branches: [main, develop]

jobs:
  pr-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.14.0

      - uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run lint and type checks
        run: |
          pnpm concurrently -g \
          "pnpm lint" \
          "pnpm typecheck" \
          "pnpm prettier --check --ignore-unknown ./" \
          "pnpm cspell ./ --no-progress --no-must-find-files"
